package admin;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import light.LightFunction;
import light.LightFunctionImpl;
import object.LightObject;
import util.ConnectionPool;

/**
 * Servlet implementation class AdminDashboard
 */
@WebServlet("/AdminDashboard")
public class AdminDashboard extends HttpServlet {
	private static final String CONTENT_TYPE = "text/html; charset= utf-8";
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public AdminDashboard() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		response.setContentType(CONTENT_TYPE);
		response.setContentType("text/html");

		PrintWriter out = response.getWriter();
		out.append("<!DOCTYPE html>");
		out.append("<html lang=\"en\">");
		out.append("");
		out.append("<head>");
		out.append("<meta charset=\"utf-8\">");
		out.append("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">");
		out.append("");
		out.append("<title>GocDecore - Sản Phẩm</title>");
		out.append("<meta content=\"\" name=\"description\">");
		out.append("<meta content=\"\" name=\"keywords\">");
		out.append("");
		out.append("<!-- Favicons -->");
		out.append("<link href=\"img/icon.png\" rel=\"icon\">");
		out.append("<link href=\"img/apple-touch-icon.png\" rel=\"apple-touch-icon\">");
		out.append("");
		out.append("<!-- Google Fonts -->");
		out.append("<link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">");
		out.append(
				"<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">");
		out.append("");
		out.append("<!-- Vendor CSS Files -->");
		out.append("<link href=\"css/css-admin-product/bootstrap.min.css\" rel=\"stylesheet\">");
		out.append("<link href=\"css/css-admin-product/bootstrap-icons.css\" rel=\"stylesheet\">");
		out.append("<link href=\"css/css-admin-product/boxicons.min.css\" rel=\"stylesheet\">");
		out.append("<link href=\"css/css-admin-product/quill.snow.css\" rel=\"stylesheet\">");
		out.append("<link href=\"css/css-admin-product/quill.bubble.css\" rel=\"stylesheet\">");
		out.append("<link href=\"css/css-admin-product/remixicon.css\" rel=\"stylesheet\">");
		out.append("<link href=\"css/css-admin-product/style_table.css\" rel=\"stylesheet\">");
		out.append("");
		out.append("<!-- Template Main CSS File -->");
		out.append("<link href=\"css/css-admin-product/style.css\" rel=\"stylesheet\">");
		out.append("</head>");
		out.append("");

		out.append("<script>");
		out.append("function getQueryParam(param) {");
		out.append("let urlParams = new URLSearchParams(window.location.search);");
		out.append("return urlParams.get(param);");
		out.append("}");

		out.append("document.addEventListener('DOMContentLoaded', function() {");
		out.append("if (getQueryParam('success') === 'true') {");
		out.append("alert('Cập nhật sản phẩm thành công!');"); // Sử dụng alert để hiển thị thông báo
		out.append("}");
		out.append("});");

		out.append("document.addEventListener('DOMContentLoaded', function() {");
		out.append("if (getQueryParam('success1') === 'true') {");
		out.append("alert('Thêm mới sản phẩm thành công!');"); // Sử dụng alert để hiển thị thông báo
		out.append("}");
		out.append("});");
		out.append("</script>");

		out.append("<body>");
		out.append("");
		out.append("<!-- ======= Header ======= -->");
		out.append("<header id=\"header\" class=\"header fixed-top d-flex align-items-center\">");
		out.append("");
		out.append("<div class=\"d-flex align-items-center justify-content-between\">");
		out.append("<a href=\"index.html\" class=\"logo d-flex align-items-center\">");
		out.append("<img src=\"img/header (2).png\" alt=\"\">");
		out.append("<span class=\"d-none d-lg-block\">Góc Decore.</span>");
		out.append("</a>");
		out.append("<i class=\"bi bi-list toggle-sidebar-btn\"></i>");
		out.append("</div><!-- End Logo -->");
		out.append("");
		out.append("<div class=\"search-bar\" >");
		out.append(
				"<form class=\"search-form d-flex align-items-center\"style=\"border-radius: 50px;\" method=\"POST\" action=\"#\">");
		out.append("<input type=\"text\" name=\"query\" placeholder=\"Tìm kiếm\" title=\"Enter search keyword\">");
		out.append("<button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\"></i></button>");
		out.append("</form>");
		out.append("</div><!-- End Search Bar -->");
		out.append("");
		out.append("<nav class=\"header-nav ms-auto\">");
		out.append("<ul class=\"d-flex align-items-center\">");
		out.append("");
		out.append("<li class=\"nav-item d-block d-lg-none\">");
		out.append("<a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">");
		out.append("<i class=\"bi bi-search\"></i>");
		out.append("</a>");
		out.append("</li><!-- End Search Icon-->");
		out.append("");
		out.append("<li class=\"nav-item dropdown\">");
		out.append("");
		out.append("<a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("<i class=\"bi bi-bell\"></i>");
		out.append("<span class=\"badge bg-danger badge-number\">2</span>");
		out.append("</a><!-- End Notification Icon -->");
		out.append("");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications\">");
		out.append("<li class=\"dropdown-header\">");
		out.append("Bạn có 2 thông báo mới");
		out.append("<a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">Xem chi tiết</span></a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li class=\"notification-item\">");
		out.append("<i class=\"bi bi-exclamation-circle text-warning\"></i>");
		out.append("<div>");
		out.append("<h4>Lorem Ipsum</h4>");
		out.append("<p>Quae dolorem earum veritatis oditseno</p>");
		out.append("<p>30 min. ago</p>");
		out.append("</div>");
		out.append("</li>");
		out.append("");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li class=\"notification-item\">");
		out.append("<i class=\"bi bi-x-circle text-danger\"></i>");
		out.append("<div>");
		out.append("<h4>Atque rerum nesciunt</h4>");
		out.append("<p>Quae dolorem earum veritatis oditseno</p>");
		out.append("<p>1 hr. ago</p>");
		out.append("</div>");
		out.append("</li>");
		out.append("");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("<li class=\"dropdown-footer\">");
		out.append("<a href=\"#\">Xem chi tiết thêm</a>");
		out.append("</li>");
		out.append("");
		out.append("</ul><!-- End Notification Dropdown Items -->");
		out.append("");
		out.append("</li><!-- End Notification Nav -->");
		out.append("");
		out.append("<li class=\"nav-item dropdown\">");
		out.append("");
		out.append("<a class=\"nav-link nav-icon\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("<i class=\"bi bi-chat-left-text\"></i>");
		out.append("<span class=\"badge bg-success badge-number\">3</span>");
		out.append("</a><!-- End Messages Icon -->");
		out.append("");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow messages\">");
		out.append("<li class=\"dropdown-header\">");
		out.append("Bạn có 3 tin nhắn mới");
		out.append("<a href=\"#\"><span class=\"badge rounded-pill bg-primary p-2 ms-2\">Xem chi tiết</span></a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li class=\"message-item\">");
		out.append("<a href=\"#\">");
		out.append("<img src=\"img/messages-1.jpg\" alt=\"\" class=\"rounded-circle\">");
		out.append("<div>");
		out.append("<h4>Maria Hudson</h4>");
		out.append("<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		out.append("<p>4 hrs. ago</p>");
		out.append("</div>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li class=\"message-item\">");
		out.append("<a href=\"#\">");
		out.append("<img src=\"img/messages-2.jpg\" alt=\"\" class=\"rounded-circle\">");
		out.append("<div>");
		out.append("<h4>Anna Nelson</h4>");
		out.append("<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		out.append("<p>6 hrs. ago</p>");
		out.append("</div>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li class=\"message-item\">");
		out.append("<a href=\"#\">");
		out.append("<img src=\"img/messages-3.jpg\" alt=\"\" class=\"rounded-circle\">");
		out.append("<div>");
		out.append("<h4>David Muldon</h4>");
		out.append("<p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>");
		out.append("<p>8 hrs. ago</p>");
		out.append("</div>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li class=\"dropdown-footer\">");
		out.append("<a href=\"#\">Xem chi tiết thêm</a>");
		out.append("</li>");
		out.append("");
		out.append("</ul><!-- End Messages Dropdown Items -->");
		out.append("");
		out.append("</li><!-- End Messages Nav -->");
		out.append("");
		out.append("<li class=\"nav-item dropdown pe-3\">");
		out.append("");
		out.append(
				"<a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">");
		out.append("<img src=\"img/profile-img.jpg\" alt=\"Profile\" class=\"rounded-circle\">");
		out.append("<span class=\"d-none d-md-block dropdown-toggle ps-2\">Hanh</span>");
		out.append("</a><!-- End Profile Iamge Icon -->");
		out.append("");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow profile\">");
		out.append("<li class=\"dropdown-header\">");
		out.append("<h6>Nguyễn Mỹ Hạnh</h6>");
		out.append("<span>Web Designer</span>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li>");
		out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">");
		out.append("<i class=\"bi bi-person\"></i>");
		out.append("<span>My Profile</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li>");
		out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"users-profile.html\">");
		out.append("<i class=\"bi bi-gear\"></i>");
		out.append("<span>Quản lý tài khoản</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li>");
		out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"pages-faq.html\">");
		out.append("<i class=\"bi bi-question-circle\"></i>");
		out.append("<span>Hỗ trợ</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<hr class=\"dropdown-divider\">");
		out.append("</li>");
		out.append("");
		out.append("<li>");
		out.append("<a class=\"dropdown-item d-flex align-items-center\" href=\"#\">");
		out.append("<i class=\"bi bi-box-arrow-right\"></i>");
		out.append("<span>Đăng xuất</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("");
		out.append("</ul><!-- End Profile Dropdown Items -->");
		out.append("</li><!-- End Profile Nav -->");
		out.append("");
		out.append("</ul>");
		out.append("</nav><!-- End Icons Navigation -->");
		out.append("");
		out.append("</header><!-- End Header -->");
		out.append("");
		out.append("<!-- ======= Sidebar ======= -->");
		out.append("<aside id=\"sidebar\" class=\"sidebar\">");
		out.append("");
		out.append("<ul class=\"sidebar-nav\" id=\"sidebar-nav\">");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append("<a class=\"nav-link \" href=\"index.html\">");
		out.append("<i class=\"bi bi-grid\"></i>");
		out.append("<span>Trang chủ</span>");
		out.append("</a>");
		out.append("</li><!-- End Trang chủ Nav -->");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append(
				"<a class=\"nav-link collapsed\" data-bs-target=\"#components-nav\" data-bs-toggle=\"collapse\" href=\"#\">");
		out.append(
				"<i class=\"bi bi-menu-button-wide\"></i><span>Chiến lược</span><i class=\"bi bi-chevron-down ms-auto\"></i>");
		out.append("</a>");
		out.append("<ul id=\"components-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">");
		out.append("<li>");
		out.append("<a href=\"components-alerts.html\">");
		out.append("<i class=\"bi bi-circle\"></i><span>Alerts</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("</ul>");
		out.append("</li><!-- End Components Nav -->");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append(
				"<a class=\"nav-link collapsed\" data-bs-target=\"#forms-nav\" data-bs-toggle=\"collapse\" href=\"#\">");
		out.append(
				"<i class=\"bi bi-journal-text\"></i><span>Đối tác</span><i class=\"bi bi-chevron-down ms-auto\"></i>");
		out.append("</a>");
		out.append("<ul id=\"forms-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">");
		out.append("<li>");
		out.append("<a href=\"forms-elements.html\">");
		out.append("<i class=\"bi bi-circle\"></i><span>Form Elements</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("</ul>");
		out.append("</li><!-- End Forms Nav -->");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append(
				"<a class=\"nav-link collapsed\" data-bs-target=\"#tables-nav\" data-bs-toggle=\"collapse\" href=\"#\">");
		out.append(
				"<i class=\"bi bi-layout-text-window-reverse\"></i><span>Sản phẩm</span><i class=\"bi bi-chevron-down ms-auto\"></i>");
		out.append("</a>");
		out.append("<ul id=\"tables-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">");
		out.append("<li>");
		out.append("<a href=\"/GocDecore/AdminLight\">");
		out.append("<i class=\"bi bi-circle\"></i><span>Danh sách sản phẩm</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("<li>");
		out.append("<a href=\"/GocDecore/AdminRating\">");
		out.append("<i class=\"bi bi-circle\"></i><span>Đánh giá của người dùng</span>");
		out.append("</a>");
		out.append("</li>");
		out.append("</ul>");
		out.append("</li><!-- End Tables Nav -->");
		out.append("");
		
		out.append("");
		out.append("<li class=\"nav-heading\">Pages</li>");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append("<a class=\"nav-link collapsed\" href=\"users-profile.html\">");
		out.append("<i class=\"bi bi-person\"></i>");
		out.append("<span>Hồ sơ cá nhân</span>");
		out.append("</a>");
		out.append("</li><!-- End Profile Page Nav -->");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append("<a class=\"nav-link collapsed\" href=\"pages-faq.html\">");
		out.append("<i class=\"bi bi-question-circle\"></i>");
		out.append("<span>F.A.Q</span>");
		out.append("</a>");
		out.append("</li><!-- End F.A.Q Page Nav -->");
		out.append("");
		out.append("<li class=\"nav-item\">");
		out.append("<a class=\"nav-link collapsed\" href=\"pages-contact.html\">");
		out.append("<i class=\"bi bi-envelope\"></i>");
		out.append("<span>Liên hệ</span>");
		out.append("</a>");
		out.append("</li><!-- End Contact Page Nav -->");
		out.append("");
		out.append("</ul>");
		out.append("");
		out.append("</aside><!-- End Sidebar-->");
		out.append("");
		out.append("<main id=\"main\" class=\"main\">");
		out.append("");
		out.append("<div class=\"pagetitle\">");
		out.append("<h1>Trang chủ</h1>");
		out.append("<nav>");
		out.append("<ol class=\"breadcrumb\">");
		out.append("<li class=\"breadcrumb-item active\"><a href=\"AdminDashboard\">Trang chủ</a></li>");
		out.append("</ol>");
		out.append("</nav>");
		out.append("</div><!-- End Page Title -->");
		out.append("");
		out.append("<section class=\"section dashboard\">");
		out.append("<div class=\"row\">");
		out.append("");
		out.append("<!-- Left side columns -->");
		out.append("<div class=\"col-lg-8\">");
		out.append("<div class=\"row\">");
		out.append("");
		out.append("<!-- Sales Card -->");
		out.append("<div class=\"col-xxl-4 col-md-6\">");
		out.append("<div class=\"card info-card sales-card\">");
		out.append("");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		out.append("<div class=\"card-body\">");
		out.append("<h5 class=\"card-title\">Danh thu <span>| hôm nay</span></h5>");
		out.append("");
		out.append("<div class=\"d-flex align-items-center\">");
		out.append("<div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">");
		out.append("<i class=\"bi bi-cart\"></i>");
		out.append("</div>");
		out.append("<div class=\"ps-3\">");
		out.append("<h6>145</h6>");
		out.append(
				"<span class=\"text-success small pt-1 fw-bold\">12%</span> <span class=\"text-muted small pt-2 ps-1\">tăng</span>");
		out.append("");
		out.append("</div>");
		out.append("</div>");
		out.append("</div>");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Sales Card -->");
		out.append("");
		out.append("<!-- Revenue Card -->");
		out.append("<div class=\"col-xxl-4 col-md-6\">");
		out.append("<div class=\"card info-card revenue-card\">");
		out.append("");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		out.append("<div class=\"card-body\">");
		out.append("<h5 class=\"card-title\">Lợi nhuận <span>| Tháng</span></h5>");
		out.append("");
		out.append("<div class=\"d-flex align-items-center\">");
		out.append("<div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">");
		out.append("<i class=\"bi bi-currency-dollar\"></i>");
		out.append("</div>");
		out.append("<div class=\"ps-3\">");
		out.append("<h7 style=\"color: #012970\">13.435.549.000 </h7>");
		out.append(
				"<span class=\"text-success small pt-1 fw-bold\">8%</span> <span class=\"text-muted small pt-2 ps-1\">increase</span>");
		out.append("");
		out.append("</div>");
		out.append("</div>");
		out.append("</div>");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Revenue Card -->");
		out.append("");
		out.append("<!-- Customers Card -->");
		out.append("<div class=\"col-xxl-4 col-xl-12\">");
		out.append("");
		out.append("<div class=\"card info-card customers-card\">");
		out.append("");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		out.append("<div class=\"card-body\">");
		out.append("<h5 class=\"card-title\">Khách hàng <span>| Năm</span></h5>");
		out.append("");
		out.append("<div class=\"d-flex align-items-center\">");
		out.append("<div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">");
		out.append("<i class=\"bi bi-people\"></i>");
		out.append("</div>");
		out.append("<div class=\"ps-3\">");
		out.append("<h6>1244</h6>");
		out.append(
				"<span class=\"text-danger small pt-1 fw-bold\">12%</span> <span class=\"text-muted small pt-2 ps-1\">tăng</span>");
		out.append("");
		out.append("</div>");
		out.append("</div>");
		out.append("");
		out.append("</div>");
		out.append("</div>");
		out.append("");
		out.append("</div><!-- End Customers Card -->");
		out.append("");
		out.append("<!-- Reports -->");
		out.append("<div class=\"col-12\">");
		out.append("<div class=\"card\">");
		out.append("");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		
		// Tim bo quan ly ket noi
		ConnectionPool cp = (ConnectionPool) getServletContext().getAttribute("CPool");
		// Tao doi tuong thuc thi chuc nang
		LightFunctionImpl lf = new LightFunctionImpl(cp);

		if (cp == null) {
			getServletContext().setAttribute("CPool", lf.getCP());
		}
		ArrayList<LightObject> list = new ArrayList<>();
		list = lf.get5MaxRevenue();		

		out.append("<div class=\"card-body\">");
		out.append("<h5 class=\"card-title\">Top 5 sản phẩm có doanh thu cao nhất <span>/Trong tháng</span></h5>");
		out.append("");
		out.append("<!-- Bar Chart -->");
		out.append("<canvas id=\"barChart\" style=\"max-height: 400px;\"></canvas>");
		out.append("<script>");
		out.append("document.addEventListener(\"DOMContentLoaded\", () => {");
		out.append("new Chart(document.querySelector('#barChart'), {");
		out.append("type: 'bar',");
		out.append("data: {");
		
		out.append("labels: ['" + list.get(0).getLight_name() + "',"
						+ " '" + list.get(1).getLight_name() + "',"
						+ " '" + list.get(2).getLight_name() + "',"
						+ " '" + list.get(3).getLight_name() + "',"
						+ " '" + list.get(4).getLight_name() + "'],");
		out.append("datasets: [{");
		out.append("label: 'Doanh thu',");
		out.append("data: ["+list.get(0).getLight_revenue()+", "+list.get(1).getLight_revenue()+", "+list.get(2).getLight_revenue()+", "+list.get(3).getLight_revenue()+", "+list.get(4).getLight_revenue()+"],");
		out.append("backgroundColor: [");
		out.append("'rgba(255, 99, 132, 0.2)',");
		out.append("'rgba(255, 205, 86, 0.2)',");
		out.append("'rgba(54, 162, 235, 0.2)',");
		out.append("'rgba(153, 102, 255, 0.2)',");
		out.append("'rgba(201, 203, 207, 0.2)'");
		out.append("],");
		out.append("borderColor: [");
		out.append("'rgb(255, 99, 132)',");
		out.append("'rgb(255, 205, 86)',");
		out.append("'rgb(54, 162, 235)',");
		out.append("'rgb(153, 102, 255)',");
		out.append("'rgb(201, 203, 207)'");
		out.append("],");
		out.append("borderWidth: 1");
		out.append("}]");
		out.append("},");
		out.append("options: {");
		out.append("scales: {");
		out.append("y: {");
		out.append("beginAtZero: true");
		out.append("}");
		out.append("}");
		out.append("}");
		out.append("});");
		out.append("});");
		out.append("</script>");
		out.append("<!-- End Bar CHart -->");
		out.append("");
		out.append("</div>");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Reports -->");
		out.append("");
		out.append("<!-- Top Selling -->");
		out.append("<div class=\"col-12\">");
		out.append("<div class=\"card top-selling overflow-auto\">");
		out.append("");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		out.append("<div class=\"card-body pb-0\">");
		out.append("<h5 class=\"card-title\">Top Bán chạy <span>| Trong tháng</span></h5>");
		out.append("");
		out.append("<table class=\"table table-borderless\">");
		out.append("<thead>");
		out.append("<tr>");
		out.append("<th scope=\"col\">Hình ảnh</th>");
		out.append("<th scope=\"col\">Sản phẩm</th>");
		out.append("<th scope=\"col\">Giá</th>");
		out.append("<th scope=\"col\">Lượt bán</th>");
		out.append("<th scope=\"col\">Doanh thu</th>");
		out.append("</tr>");
		out.append("</thead>");
		out.append("<tbody>");
		
		ArrayList<LightObject> list1 = new ArrayList<>();
		list1 = lf.get5MaxSales_count();	
		for(LightObject item : list1) {
			out.append("<tr>");
			out.append("<th scope=\"row\"><a href=\"#\"><img src=\"img/light_img/"+item.getLight_img()+".jpg\" alt=\"\"></a></th>");
			out.append("<td><a href=\"#\" class=\"text-info fw-bold\">"+item.getLight_name()+"</a></td>");
			DecimalFormat df = new DecimalFormat("#,###");
			out.append("<td>"+df.format(item.getLight_price())+"</td>");
			out.append("<td class=\"fw-bold\">"+item.getSales_count()+"</td>");
			out.append("<td>"+df.format(item.getLight_revenue())+"</td>");
			out.append("</tr>");
			out.append("<tr>");
		}

		out.append("</tbody>");
		out.append("</table>");
		out.append("");
		out.append("</div>");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Top Selling -->");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Left side columns -->");
		out.append("");
		out.append("<!-- Right side columns -->");
		out.append("<div class=\"col-lg-4\">");
		out.append("");
		out.append("<!-- Recent Activity -->");
		out.append("<div class=\"card\">");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		out.append("<div class=\"card-body\">");
		out.append("<h5 class=\"card-title\">Hoạt động gần đây <span>| Hôm nay</span></h5>");
		out.append("");
		out.append("<div class=\"activity\">");
		out.append("");
		out.append("<div class=\"activity-item d-flex\">");
		out.append("<div class=\"activite-label\">32 phút</div>");
		out.append("<i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>");
		out.append("<div class=\"activity-content\">");
		out.append("Cập nhật <a href=\"#\" class=\"fw-bold text-dark\">sản phẩm</a> ");
		out.append("</div>");
		out.append("</div><!-- End activity item-->");
		out.append("");
		out.append("<div class=\"activity-item d-flex\">");
		out.append("<div class=\"activite-label\">43 phút</div>");
		out.append("<i class='bi bi-circle-fill activity-badge text-danger align-self-start'></i>");
		out.append("<div class=\"activity-content\">");
		out.append("Xem dữ liệu khách hàng, xem đánh giá và phản hồi của khách hàng");
		out.append("</div>");
		out.append("</div><!-- End activity item-->");
		out.append("");
		out.append("<div class=\"activity-item d-flex\">");
		out.append("<div class=\"activite-label\">3 giờ</div>");
		out.append("<i class='bi bi-circle-fill activity-badge text-primary align-self-start'></i>");
		out.append("<div class=\"activity-content\">");
		out.append("Cập nhật sản phẩm bán chạy, Thêm sản phẩm mới");
		out.append("</div>");
		out.append("</div><!-- End activity item-->");
		out.append("");
		out.append("<div class=\"activity-item d-flex\">");
		out.append("<div class=\"activite-label\">1 day</div>");
		out.append("<i class='bi bi-circle-fill activity-badge text-info align-self-start'></i>");
		out.append("<div class=\"activity-content\">");
		out.append(
				"Cập nhật bảng doanh số của tháng những <a href=\"#\" class=\"fw-bold text-dark\">Sản phẩm</a> theo danh mục");
		out.append("</div>");
		out.append("</div><!-- End activity item-->");
		out.append("");
		out.append("</div>");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Recent Activity -->");
		out.append("");
		out.append("<!-- Website Traffic -->");
		out.append("<div class=\"card\">");
		out.append("<div class=\"filter\">");
		out.append("<a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>");
		out.append("<ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">");
		out.append("<li class=\"dropdown-header text-start\">");
		out.append("<h6>Filter</h6>");
		out.append("</li>");
		out.append("");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Hôm nay</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Tháng</a></li>");
		out.append("<li><a class=\"dropdown-item\" href=\"#\">Năm</a></li>");
		out.append("</ul>");
		out.append("</div>");
		out.append("");
		out.append("<div class=\"card-body pb-0\">");
		out.append("<h5 class=\"card-title\">Lượng truy cập website<span>| Hôm nay</span></h5>");
		out.append("");
		out.append("<div id=\"trafficChart\" style=\"min-height: 400px;\" class=\"echart\"></div>");
		out.append("");
		out.append("<script>");
		out.append("document.addEventListener(\"DOMContentLoaded\", () => {");
		out.append("echarts.init(document.querySelector(\"#trafficChart\")).setOption({");
		out.append("tooltip: {");
		out.append("trigger: 'item'");
		out.append("},");
		out.append("legend: {");
		out.append("top: '5%',");
		out.append("left: 'center'");
		out.append("},");
		out.append("series: [{");
		out.append("name: 'Access From',");
		out.append("type: 'pie',");
		out.append("radius: ['40%', '70%'],");
		out.append("avoidLabelOverlap: false,");
		out.append("label: {");
		out.append("show: false,");
		out.append("position: 'center'");
		out.append("},");
		out.append("emphasis: {");
		out.append("label: {");
		out.append("show: true,");
		out.append("fontSize: '18',");
		out.append("fontWeight: 'bold'");
		out.append("}");
		out.append("},");
		out.append("labelLine: {");
		out.append("show: false");
		out.append("},");
		out.append("data: [{");
		out.append("value: 1048,");
		out.append("name: 'Search Engine'");
		out.append("},");
		out.append("{");
		out.append("value: 735,");
		out.append("name: 'Direct'");
		out.append("},");
		out.append("{");
		out.append("value: 580,");
		out.append("name: 'Email'");
		out.append("},");
		out.append("{");
		out.append("value: 484,");
		out.append("name: 'Union Ads'");
		out.append("},");
		out.append("{");
		out.append("value: 300,");
		out.append("name: 'Video Ads'");
		out.append("}");
		out.append("]");
		out.append("}]");
		out.append("});");
		out.append("});");
		out.append("</script>");
		out.append("");
		out.append("</div>");
		out.append("</div><!-- End Website Traffic -->");
		out.append("");
		out.append("          ");
		out.append("");
		out.append("</div><!-- End Right side columns -->");
		out.append("");
		out.append("</div>");
		out.append("</section>");
		out.append("");
		out.append("</main><!-- End #main -->");
		out.append("");
		out.append(
				"<a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>");
		out.append("");
		out.append("<!-- Vendor JS Files -->");
		out.append("<script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>");
		out.append("<script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>");
		out.append("<script src=\"assets/vendor/chart.js/chart.umd.js\"></script>");
		out.append("<script src=\"assets/vendor/echarts/echarts.min.js\"></script>");
		out.append("<script src=\"assets/vendor/quill/quill.js\"></script>");
		out.append("<script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>");
		out.append("<script src=\"assets/vendor/tinymce/tinymce.min.js\"></script>");
		out.append("<script src=\"assets/vendor/php-email-form/validate.js\"></script>");
		out.append("");
		out.append("<!-- Template Main JS File -->");
		out.append("<script src=\"assets/js/main.js\"></script>");
		out.append("");
		out.append("</body>");
		out.append("");
		out.append("</html>");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
